services:
  web:
    build: ./app
    container_name: web4mongo
    ports:
      - 80:80
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - ${PWD}/app:/var/www/html
      - ${PWD}/logs:/var/log/apache2

  mongo:
    image: mongo
    container_name: mongodb
    volumes:
      - ${PWD}/mongo-data/configdb:/data/configdb
      - ${PWD}/mongo-data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopwd

  mongo-express:
    image: mongo-express
    container_name: mongoex
    ports:
      - 8081:8081     
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopwd
      ME_CONFIG_MONGODB_URL: mongodb://root:mongopwd@mongo:27017/
    links:
      - mongo
    depends_on:
      - mongo


  # docker compose rm -fsv