DROP DATABASE if EXISTS Animals;
CREATE DATABASE Animals;

USE Animals;

CREATE TABLE Pets (
    Id INT PRIMARY KEY AUTO_INCREMENT, 
    Name VARCHAR(20),
    Type VARCHAR(20),
    Age FLOAT,
    Owner VARCHAR(20),
    Vacc TINYINT);

